import io
import pandas as pd
from typing import Dict, Any, List
from reportlab.lib.pagesizes import letter
from reportlab.lib import colors
from reportlab.lib.styles import getSampleStyleSheet, ParagraphStyle
from reportlab.platypus import SimpleDocTemplate, Paragraph, Spacer, Table, TableStyle, HRFlowable, KeepTogether
from app.services.gemini_service import generate_text_response

def generate_pdf_report(dataset_filename: str, df: pd.DataFrame, kpi_list: List[Dict[str, Any]], ml_sales_info: Dict[str, Any], ml_churn_info: Dict[str, Any]) -> bytes:
    buffer = io.BytesIO()
    doc = SimpleDocTemplate(
        buffer,
        pagesize=letter,
        rightMargin=40, leftMargin=40, topMargin=40, bottomMargin=40
    )

    styles = getSampleStyleSheet()
    
    # Custom Palette
    PRIMARY = colors.HexColor("#1e293b")
    ACCENT = colors.HexColor("#3b82f6")
    TEXT_DARK = colors.HexColor("#334155")
    BG_LIGHT = colors.HexColor("#f8fafc")

    title_style = ParagraphStyle(
        'DocTitle',
        parent=styles['Heading1'],
        fontName='Helvetica-Bold',
        fontSize=24,
        leading=28,
        textColor=PRIMARY
    )
    
    subtitle_style = ParagraphStyle(
        'DocSubTitle',
        parent=styles['Normal'],
        fontName='Helvetica',
        fontSize=10,
        leading=14,
        textColor=colors.HexColor("#64748b")
    )

    heading2_style = ParagraphStyle(
        'Heading2Custom',
        parent=styles['Heading2'],
        fontName='Helvetica-Bold',
        fontSize=14,
        leading=18,
        textColor=PRIMARY,
        spaceBefore=12,
        spaceAfter=6
    )

    body_style = ParagraphStyle(
        'BodyCustom',
        parent=styles['BodyText'],
        fontName='Helvetica',
        fontSize=10,
        leading=14,
        textColor=TEXT_DARK
    )

    story = []

    # Title & Metadata
    story.append(Paragraph("DataCopilot AI — Executive Intelligence Report", title_style))
    story.append(Paragraph(f"Dataset: <b>{dataset_filename}</b> | Generated by DataCopilot AI Engine", subtitle_style))
    story.append(Spacer(1, 10))
    story.append(HRFlowable(width="100%", thickness=1.5, color=ACCENT, spaceBefore=5, spaceAfter=15))

    # 1. Executive Summary & Recommendations (Gemini Generated)
    prompt = (
        f"Generate a concise 2-paragraph executive summary and 4 bullet point business recommendations based on this dataset:\n"
        f"- File: {dataset_filename}\n"
        f"- Total Rows: {len(df)}\n"
        f"- KPI Metrics: {kpi_list}\n"
        f"- Sales Model Score (R²): {ml_sales_info.get('r2_score', 'N/A')}\n"
        f"- Churn Model Risk Count: {ml_churn_info.get('high_risk_count', 'N/A')}\n\n"
        "Format with clear headings: 'Executive Overview' and 'Strategic Recommendations'."
    )
    ai_exec_summary = generate_text_response(prompt, system_instruction="You are a senior data analyst. Provide actionable, concise business insights.")
    
    story.append(Paragraph("1. Executive Overview & AI Insights", heading2_style))
    for paragraph_text in ai_exec_summary.split("\n"):
        if paragraph_text.strip():
            story.append(Paragraph(paragraph_text.strip(), body_style))
            story.append(Spacer(1, 4))

    story.append(Spacer(1, 10))

    # 2. Key Performance Indicators Table
    story.append(Paragraph("2. Key Performance Indicators", heading2_style))
    
    table_data = [["KPI Metric", "Value", "Context / Subtext"]]
    for kpi in kpi_list:
        table_data.append([
            kpi.get('title', ''),
            kpi.get('value', ''),
            kpi.get('subtext', '')
        ])

    kpi_table = Table(table_data, colWidths=[180, 140, 210])
    kpi_table.setStyle(TableStyle([
        ('BACKGROUND', (0,0), (-1,0), PRIMARY),
        ('TEXTCOLOR', (0,0), (-1,0), colors.white),
        ('FONTNAME', (0,0), (-1,0), 'Helvetica-Bold'),
        ('FONTSIZE', (0,0), (-1,0), 10),
        ('ALIGN', (0,0), (-1,-1), 'LEFT'),
        ('VALIGN', (0,0), (-1,-1), 'MIDDLE'),
        ('BACKGROUND', (0,1), (-1,-1), BG_LIGHT),
        ('GRID', (0,0), (-1,-1), 0.5, colors.HexColor("#cbd5e1")),
        ('TOPPADDING', (0,0), (-1,-1), 6),
        ('BOTTOMPADDING', (0,0), (-1,-1), 6),
    ]))
    story.append(kpi_table)
    story.append(Spacer(1, 15))

    # 3. Machine Learning Analytics Summary
    story.append(Paragraph("3. Predictive Analytics Summary", heading2_style))
    
    ml_data = [
        ["Model Type", "Status", "Primary Accuracy / Metric", "Key Findings"],
        [
            "Sales Forecast (Regression)",
            "Active" if ml_sales_info.get("supported") else "N/A",
            f"R² Score: {ml_sales_info.get('r2_score', 'N/A')} (MAE: ${ml_sales_info.get('mae', 'N/A')})",
            f"Trained on {ml_sales_info.get('date_column', 'date')} vs {ml_sales_info.get('target_column', 'sales')}"
        ],
        [
            "Customer Churn (RandomForest)",
            "Active" if ml_churn_info.get("supported") else "Not Applicable",
            f"Accuracy: {ml_churn_info.get('accuracy', 'N/A')}",
            f"High Risk Churn Customers Detected: {ml_churn_info.get('high_risk_count', 0)}"
        ]
    ]

    ml_table = Table(ml_data, colWidths=[160, 90, 140, 140])
    ml_table.setStyle(TableStyle([
        ('BACKGROUND', (0,0), (-1,0), ACCENT),
        ('TEXTCOLOR', (0,0), (-1,0), colors.white),
        ('FONTNAME', (0,0), (-1,0), 'Helvetica-Bold'),
        ('FONTSIZE', (0,0), (-1,0), 9),
        ('GRID', (0,0), (-1,-1), 0.5, colors.HexColor("#cbd5e1")),
        ('TOPPADDING', (0,0), (-1,-1), 6),
        ('BOTTOMPADDING', (0,0), (-1,-1), 6),
    ]))
    story.append(ml_table)
    story.append(Spacer(1, 15))

    # 4. Dataset Preview Snapshot
    story.append(Paragraph("4. Dataset Sample Records", heading2_style))
    
    preview_rows = df.head(5)
    cols = list(preview_rows.columns)[:5]
    prev_table_data = [[str(c) for c in cols]]
    
    for _, r in preview_rows.iterrows():
        prev_table_data.append([str(r[c])[:20] for c in cols])

    prev_table = Table(prev_table_data, colWidths=[100]*len(cols))
    prev_table.setStyle(TableStyle([
        ('BACKGROUND', (0,0), (-1,0), colors.HexColor("#64748b")),
        ('TEXTCOLOR', (0,0), (-1,0), colors.white),
        ('FONTNAME', (0,0), (-1,0), 'Helvetica-Bold'),
        ('FONTSIZE', (0,0), (-1,0), 8),
        ('GRID', (0,0), (-1,-1), 0.5, colors.HexColor("#e2e8f0")),
        ('TOPPADDING', (0,0), (-1,-1), 4),
        ('BOTTOMPADDING', (0,0), (-1,-1), 4),
    ]))
    story.append(prev_table)

    # Footer notice
    story.append(Spacer(1, 20))
    story.append(HRFlowable(width="100%", thickness=0.5, color=colors.HexColor("#cbd5e1")))
    story.append(Paragraph("DataCopilot AI — Confidential Business Intelligence Report", subtitle_style))

    doc.build(story)
    pdf_bytes = buffer.getvalue()
    buffer.close()
    return pdf_bytes
